# main.yml

# Workflow's name
name: Build

# Workflow's trigger
on:
  push:
    branches:
      - master

# 给 GITHUB_TOKEN 提升权限
permissions:
  contents: write  # 允许写入 Release
  
# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-2022, ubuntu-latest]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v4

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'yarn'
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # step3: install system dependencies (Linux only)
      - name: Install system deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libxtst-dev libpng++-dev
          sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
          sudo snap install snapcraft --classic
      
      # step4: yarn
      - name: Yarn install
        run: |
          yarn
          yarn global add xvfb-maybe
          yarn global add @vue/cli@4.5.0  --frozen-lockfile --ignore-engines

      # step5: build feature
      - name: Build feature
        run: |
          cd ./feature
          yarn
          npm run build
          
      # step6: build and release app
      # - name: Build  & release app
      #   run: |
      #     npm run release
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build/Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          # 如果是推送到 tag，则自动创建 Release 并上传二进制文件
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          # 针对 Node 16 的环境，有时需要禁用某些硬限制
          max_attempts: 3

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.deb
            dist/*.zip
